import {
    type Content,
    type HandlerCallback,
    type IAgentRuntime,
    type Memory,
    ModelClass,
    type State,
    type UUID,
    generateMessageResponse,
    elizaLogger,
    stringToUuid,
    getEmbeddingZeroVector,
    composeContext,
    generateText,
} from "@elizaos/core";
import type { AirificaIncomingMessage, AirificaMessageContent, AirificaMessageEnvelope, TradeProposal } from "./types.ts";

// Minimal fallback template — character.templates.messageHandlerTemplate takes priority if set
const AIRIFICA_DEFAULT_TEMPLATE = `# CONVERSATION CONTEXT
{{recentMessages}}

{{pacificaContextBlock}}

# TASK
You are {{agentName}}, an AI trading assistant.
Respond to the user's last message in a concise, helpful way.
Write plain text only. Do not return JSON, markdown code fences, XML tags, or hidden routing metadata.
`;

const TRADE_PROPOSAL_ACTIONS = new Set([
    "GET_CRYPTO_CHART",
    "GET_TOKEN_CHART",
    "GET_CRYPTO_ANALYSIS",
    "GET_TOKEN_ANALYSIS",
]);

const TRADE_PARSER_SYSTEM_PROMPT = [
    "You validate a trading setup extracted from an Airifica market analysis generated by another LLM.",
    "Return exactly one pure JSON object with keys {symbol, side, entry, tp, sl} and optionally {reason}.",
    "Mandatory rules:",
    "- symbol must be a single uppercase ticker with only letters or numbers.",
    "- side must be LONG or SHORT.",
    "- entry, tp, sl must come from the message. Never invent missing prices.",
    "- LONG requires sl < entry < tp. SHORT requires tp < entry < sl.",
    "- Ignore indicator names and metadata such as EMA24, EMA168, RSI14, VWAP, 1H, percentages, candle counts, dates, confidence scores.",
    "- If the text says to stay out, has no executable setup, or the levels are inconsistent, return null fields with a reason.",
    "- Output JSON only. No prose, no markdown fences.",
    "Valid example: {\"symbol\":\"BCH\",\"side\":\"SHORT\",\"entry\":449.5,\"tp\":442.4,\"sl\":458.0}",
    "Fallback example: {\"symbol\":null,\"side\":null,\"entry\":null,\"tp\":null,\"sl\":null,\"reason\":\"no valid setup\"}",
].join(" ");

function buildActionRoutingPrompt(originalText: string) {
    return `
<|system init|>.

ROLE.
You are CryptoFormatter-Pro, a strict pre-processor for routing.
Return exactly one final line wrapped in <out>...</out>. No logs, no thoughts, no extra text.

INPUT.
USER RAW TEXT: ${originalText}.

REWRITING RULES.
1) CONTRACT ADDRESSES.
- Detect EVM: 0x[a-fA-F0-9]{40}.
- Detect base58: 25-60 characters.
- Leave addresses unchanged and exclude them from ticker analysis.
- If there is EXACTLY ONE address and no other clear context -> add the keyword tokenPrice.

2) TICKERS (non-address).
- Detect standalone symbols of 2-6 characters (BTC, ETH, SOL, etc.), not inside addresses.
- Normalize to uppercase and ensure the $ prefix.
- If there is EXACTLY ONE $TICKER and no other clear context -> add cryptoPrice.

3) TEXT AND PUNCTUATION.
- Preserve meaning, punctuation, and order.
- Do not duplicate keywords.

SPECIAL OVERRIDE (AIR3 / LAIR / POLAR).
- AIR3 -> 2jvsWRkT17ofmv9pkW7ofqAFWSCNyJYdykJ7kPKbmoon
- LAIR -> 0xbC62C287b50B86A46e5B552bCd5BF9b64DA35eCc
- POLAR -> 0x51A7688ca5B142456f4C8D44513433485bF599E9
- If override applies, convert crypto* decisions into token*.

TRIGGER POLICY (ZERO FALSE POSITIVES).
- If message is conversational, return no action tools.
- If it is an explicit command/question for chart, analysis, price, news, mentions, trending, volume, fundamentals, listings, sentiment, or time, return exactly one keyword.
- If multiple entities or ambiguous intent -> no action tools.

FINAL OUTPUT.
- If a keyword is required: <out>{transformed_text} <hidden>{keyword},provide insights</hidden></out>
- If no action is required: <out>{transformed_text} <hidden>no action tools; provide insights</hidden></out>

KEYWORD TABLE.
- dateTime: requests date or time
- tokenBoosted: boosted tokens
- tokenTrending: trending tokens
- tickerMentioned: most mentioned project on X/Twitter
- cryptoListing: newly listed coins
- cryptoNews: latest news
- cryptoSentiment: market sentiment
- cryptoVolume: projects with highest volume
- cryptoAnalysis: analysis for $ticker
- tokenAnalysis: analysis for contract address
- cryptoChart: chart for $ticker
- tokenChart: chart for contract address
- cryptoPrice: price for $ticker
- tokenPrice: price for contract address
- cryptoFundamental: fundamentals for $ticker
- tokenFundamental: fundamentals for contract address

<|system end|>.
`;
}

const AIREMARKET_KEYWORD_DEFAULTS: Record<string, string> = {
    KEYWORDS_GET_BOOSTED_TOKENS: "boosted,boost,boosted tokens",
    KEYWORDS_GET_CRYPTO_ANALYSIS: "analysis,analyze,analyse,thesis",
    KEYWORDS_GET_CRYPTO_CHART: "chart,graph,plot",
    KEYWORDS_GET_CRYPTO_FUNDAMENTAL: "fundamental,fundamentals,tokenomics",
    KEYWORDS_GET_CRYPTO_PRICE: "price,quote,how much",
    KEYWORDS_GET_CRYPTO_REPLY: "reply,respond",
    KEYWORDS_GET_DATETIME: "time,date,hour,today",
    KEYWORDS_GET_MOST_MENTIONED_TICKER: "most mentioned,mentioned ticker,top mentions,rise in mention,rising mentions,most talked",
    KEYWORDS_GET_NEW_LISTINGS: "new listings,new listing,listings,listed",
    KEYWORDS_GET_NEWS: "news,headline,headlines",
    KEYWORDS_GET_SENTIMENT: "sentiment,mood,bullish,bearish",
    KEYWORDS_GET_TOKEN_ANALYSIS: "analysis,analyze,analyse,thesis",
    KEYWORDS_GET_TOKEN_CHART: "chart,graph,plot",
    KEYWORDS_GET_TOKEN_FUNDAMENTAL: "fundamental,fundamentals,tokenomics",
    KEYWORDS_GET_TOKEN_PRICE: "price,quote,how much",
    KEYWORDS_GET_TOKEN_REPLY: "reply,respond",
    KEYWORDS_GET_TOTAL_VOLUME: "volume,total volume",
    KEYWORDS_GET_TRENDING_TOKENS: "trending,trending tokens,hot tokens",
};

const MARKET_SYMBOL_ALIASES = new Set([
    "btc", "eth", "sol", "sui", "xrp", "avax", "bnb", "doge", "ada", "link",
    "ltc", "dot", "atom", "apt", "arb", "op", "near", "inj", "sei", "rndr",
    "wif", "bonk", "fartcoin", "hype", "bera",
]);

const MARKET_SYMBOL_STOPWORDS = new Set([
    "USD", "USDT", "USDC", "EUR", "LONG", "SHORT", "BUY", "SELL", "NEWS",
    "CHART", "PRICE", "MARKET", "TOKEN", "TOKENS", "TRADE", "VOLUME",
    "ANALYSIS", "ANALYZE", "ANALYSE", "MENTIONED", "TOP", "MOST",
]);

const MARKET_INTENT_PATTERN = /\b(chart|graph|plot|analysis|analyze|analyse|price|quote|worth|cost|news|headline|sentiment|volume|listing|listed|trending|boosted|mentions?|ticker|token|tokens|contract|address|ca\b|crypto|coin|coins|market|markets|trade|trading|long|short|buy|sell|entry|take profit|stop loss|tp\b|sl\b|wallet|position|positions|portfolio|pnl|fundamental|fundamentals|tokenomics|pacifica|jupiter|perp|spot)\b/i;
const ACTION_MARKET_INTENT_PATTERN = /\b(chart|graph|plot|analysis|analyze|analyse|price|quote|worth|cost|news|headline|sentiment|volume|listing|listed|trending|boosted|mentions?|ticker|token|tokens|contract|address|ca\b|crypto|coin|coins|market|markets|trade|trading|long|short|buy|sell|entry|take profit|stop loss|tp\b|sl\b|fundamental|fundamentals|tokenomics|jupiter|perp|spot)\b/i;
const ACTION_ROUTER_HIGH_SIGNAL_PATTERN = /\b(chart|graph|plot|analysis|analyze|analyse|price|quote|worth|cost|news|headline|sentiment|volume|listing|listed|trending|boosted|mentions?|fundamental|fundamentals|tokenomics)\b/i;
const ACCOUNT_INTENT_PATTERN = /\b(open position|open positions|position|positions|portfolio|account|equity|available|withdrawable|margin|pnl|profit|loss|liquidation|liq|exposure|ready to trade|risk|overexposed|close now|hold now|reduce risk|execution state)\b/i;
const CONVERSATIONAL_FAST_PATH_PATTERN = /\b(hi|hello|hey|yo|gm|gn|good morning|good evening|good night|how are you|how's it going|how is it going|what's up|whats up|who are you|thanks|thank you|ok|okay|cool|nice|great|perfect|understood|got it|help me|help)\b/i;

const TOKEN_ALIAS_OVERRIDES: Record<string, string> = {
    AIR3: "2jvsWRkT17ofmv9pkW7ofqAFWSCNyJYdykJ7kPKbmoon",
    LAIR: "0xbC62C287b50B86A46e5B552bCd5BF9b64DA35eCc",
    POLAR: "0x51A7688ca5B142456f4C8D44513433485bF599E9",
};

const EVM_ADDRESS_PATTERN = /\b0x[a-fA-F0-9]{40}\b/g;
const BASE58_ADDRESS_PATTERN = /\b[1-9A-HJ-NP-Za-km-z]{25,60}\b/g;
const EXPLICIT_TICKER_PATTERN = /\$([A-Z0-9]{2,12})\b/g;

const ROUTER_KEYWORD_TO_ACTION: Record<string, string> = {
    dateTime: "GET_DATETIME",
    tokenBoosted: "GET_BOOSTED_TOKENS",
    tokenTrending: "GET_TRENDING_TOKENS",
    tickerMentioned: "GET_MOST_MENTIONED_TICKER",
    cryptoListing: "GET_NEW_LISTINGS",
    cryptoNews: "GET_NEWS",
    cryptoSentiment: "GET_SENTIMENT",
    cryptoVolume: "GET_TOTAL_VOLUME",
    cryptoAnalysis: "GET_CRYPTO_ANALYSIS",
    tokenAnalysis: "GET_TOKEN_ANALYSIS",
    cryptoChart: "GET_CRYPTO_CHART",
    tokenChart: "GET_TOKEN_CHART",
    cryptoPrice: "GET_CRYPTO_PRICE",
    tokenPrice: "GET_TOKEN_PRICE",
    cryptoFundamental: "GET_CRYPTO_FUNDAMENTAL",
    tokenFundamental: "GET_TOKEN_FUNDAMENTAL",
};

type RoutedActionPlan = {
    keyword: string | null;
    routedText: string;
    raw: string;
    source: "deterministic" | "llm-small" | "llm-large";
    candidateActions: string[];
};

type PacificaKnowledgePayload = {
    pacifica_status?: {
        readyToExecute?: boolean;
        hasBinding?: boolean;
        builderApproved?: boolean;
        agentBound?: boolean;
        isActive?: boolean;
        agentWalletPublicKey?: string;
        pacificaAccount?: string;
        builderCode?: string;
    } | null;
    pacifica_account?: {
        equity_usd?: number;
        available_to_spend_usd?: number;
        available_to_withdraw_usd?: number;
        total_margin_used_usd?: number;
        positions_count?: number;
        orders_count?: number;
        stop_orders_count?: number;
        maker_fee_rate?: number;
        taker_fee_rate?: number;
        updated_at?: number;
    } | null;
    account_missing?: boolean;
    onboarding_hint?: string | null;
    minimum_deposit_usd?: number | null;
    open_positions?: Array<{
        symbol?: string;
        side?: string;
        amount?: number;
        entry_price?: number;
        mark_price?: number;
        take_profit_price?: number;
        stop_loss_price?: number;
        liquidation_price?: number;
        notional_usd?: number;
        margin_usd?: number;
        funding_rate?: number;
        unrealized_pnl_usd?: number;
        unrealized_pnl_pct?: number;
        isolated?: boolean;
        updated_at?: number;
    }>;
};

/**
 * AirificaMessageManager mirrors the minimal web chat message flow:
 *   ensureConnection → createMemory → processActions → fallback LLM → processActions → evaluate
 *
 * Identity model (deterministic, wallet-scoped):
 *   userId  = uuid5("airifica:user:" + walletAddress)
 *   roomId  = uuid5("airifica:room:" + walletAddress + ":" + conversationId)
 *   source  = "airifica"
 */
export class AirificaMessageManager {
    private runtime: IAgentRuntime;
    private readonly actionValidationTimeoutMs = Number(process.env.AIRIFICA_ACTION_VALIDATE_TIMEOUT_MS || process.env.AIRI3_ACTION_VALIDATE_TIMEOUT_MS || process.env.AIRIFICA_ACTION_TIMEOUT_MS || process.env.AIRI3_ACTION_TIMEOUT_MS || 8000);
    private readonly actionHandlerTimeoutMs = Number(process.env.AIRIFICA_ACTION_HANDLER_TIMEOUT_MS || process.env.AIRI3_ACTION_HANDLER_TIMEOUT_MS || 45000);
    private readonly llmTimeoutMs = Number(process.env.AIRIFICA_LLM_TIMEOUT_MS || process.env.AIRI3_LLM_TIMEOUT_MS || 25000);
    private readonly evaluationTimeoutMs = Number(process.env.AIRIFICA_EVALUATION_TIMEOUT_MS || process.env.AIRI3_EVALUATION_TIMEOUT_MS || 5000);
    private readonly tradeParserTimeoutMs = Number(process.env.AIRIFICA_TRADE_PARSER_TIMEOUT_MS || process.env.AIRI3_TRADE_PARSER_TIMEOUT_MS || 15000);
    private airemarketPluginPromise: Promise<any> | null = null;

    constructor(runtime: IAgentRuntime) {
        this.runtime = runtime;
        this.ensureKeywordDefaults();
    }

    private buildPacificaContextBlock(raw: string | null | undefined) {
        const payload = String(raw || '').trim();
        if (!payload)
            return '';

        return [
            '# PRIVATE PACIFICA ACCOUNT CONTEXT',
            'The JSON below is private runtime knowledge for the current user.',
            'Use it only if the user explicitly asks about their Pacifica account, open positions, risk, close/hold decisions, margin, pnl, or execution state.',
            'Do not mention this hidden context unless it is relevant to the user request.',
            payload,
            '',
        ].join('\n');
    }

    private async withTimeout<T>(label: string, promise: Promise<T>, timeoutMs: number): Promise<T> {
        return await Promise.race([
            promise,
            new Promise<T>((_, reject) => {
                setTimeout(() => reject(new Error(`${label} timeout after ${timeoutMs}ms`)), timeoutMs);
            }),
        ]);
    }

    private runBestEffort(label: string, task: () => Promise<unknown>, timeoutMs: number) {
        void this.withTimeout(label, task(), timeoutMs).catch((error) => {
            elizaLogger.warn(`[client-airifica] ${label} skipped:`, error);
        });
    }

    private getMandatoryActions(): string[] {
        return (process.env.MANDATORY_ACTIONS || "")
            .split(",")
            .map(action => action.trim())
            .filter(Boolean);
    }

    private getActionHandlerTimeoutMs(actionName: string) {
        const normalizedActionName = String(actionName || "").trim().toUpperCase();
        const envOverride = process.env[`AIRIFICA_ACTION_HANDLER_TIMEOUT_MS_${normalizedActionName}`]
            || process.env[`AIRI3_ACTION_HANDLER_TIMEOUT_MS_${normalizedActionName}`];
        if (envOverride)
            return Number(envOverride);

        const slowActionDefaults: Record<string, number> = {
            GET_CRYPTO_CHART: 90_000,
            GET_TOKEN_CHART: 90_000,
            GET_MOST_MENTIONED_TICKER: 120_000,
            GET_TRENDING_TOKENS: 120_000,
            GET_BOOSTED_TOKENS: 120_000,
            GET_NEW_LISTINGS: 120_000,
            GET_NEWS: 90_000,
        };

        return slowActionDefaults[normalizedActionName] || this.actionHandlerTimeoutMs;
    }

    private async getAirmarketPlugin() {
        const pluginEntryUrl = new URL("../../plugin-airemarket/dist/index.js", import.meta.url).href;
        this.airemarketPluginPromise ??= import(pluginEntryUrl).then(mod => mod.default);
        return await this.airemarketPluginPromise;
    }

    private ensureKeywordDefaults() {
        for (const [key, fallback] of Object.entries(AIREMARKET_KEYWORD_DEFAULTS)) {
            if (!process.env[key]?.trim())
                process.env[key] = fallback;
        }
    }

    private extractUniqueMatches(text: string, pattern: RegExp) {
        const matches = text.match(pattern) || [];
        return [...new Set(matches)];
    }

    private extractExplicitTickers(text: string) {
        const tickers = new Set<string>();
        const upperText = text.toUpperCase();
        let match: RegExpExecArray | null;
        const pattern = new RegExp(EXPLICIT_TICKER_PATTERN);
        while ((match = pattern.exec(upperText)) !== null) {
            const ticker = match[1]?.toUpperCase().trim();
            if (ticker && !MARKET_SYMBOL_STOPWORDS.has(ticker))
                tickers.add(ticker);
        }
        return [...tickers];
    }

    private extractOverrideAddresses(text: string) {
        const matches: string[] = [];
        const upperText = text.toUpperCase();

        for (const [alias, address] of Object.entries(TOKEN_ALIAS_OVERRIDES)) {
            const regex = new RegExp(`\\b${alias}\\b`, "i");
            if (regex.test(upperText))
                matches.push(address);
        }

        return [...new Set(matches)];
    }

    private replaceOverrideAliases(text: string) {
        let transformed = text;
        for (const [alias, address] of Object.entries(TOKEN_ALIAS_OVERRIDES))
            transformed = transformed.replace(new RegExp(`\\b${alias}\\b`, "gi"), address);
        return transformed;
    }

    private resolveRouteCandidateActions(keyword: string | null) {
        if (!keyword)
            return [];

        const actionName = ROUTER_KEYWORD_TO_ACTION[keyword];
        return actionName ? [actionName] : [];
    }

    private buildDeterministicActionRoute(originalText: string, normalizedText: string): RoutedActionPlan | null {
        const transformedText = this.replaceOverrideAliases(normalizedText);
        const lowered = originalText.toLowerCase();
        const addresses = [
            ...this.extractUniqueMatches(transformedText, EVM_ADDRESS_PATTERN),
            ...this.extractUniqueMatches(transformedText, BASE58_ADDRESS_PATTERN),
            ...this.extractOverrideAddresses(normalizedText),
        ];
        const uniqueAddresses = [...new Set(addresses)];
        const tickers = this.extractExplicitTickers(transformedText);
        const hasSingleAddress = uniqueAddresses.length === 1 && tickers.length === 0;
        const hasSingleTicker = tickers.length === 1 && uniqueAddresses.length === 0;

        const buildPlan = (keyword: keyof typeof ROUTER_KEYWORD_TO_ACTION, visibleText: string) => ({
            keyword,
            routedText: `${keyword} ${visibleText.trim()}`.trim(),
            raw: `<out>${visibleText.trim()} <hidden>${keyword},provide insights</hidden></out>`,
            source: "deterministic" as const,
            candidateActions: this.resolveRouteCandidateActions(keyword),
        });

        if (/\b(what time|what's the time|current time|current date|today'?s date|date today|che ore|che ora|what day is it)\b/i.test(lowered))
            return buildPlan("dateTime", transformedText || originalText);

        if (/\b(boosted tokens?|token boosts?|top boosts?)\b/i.test(lowered))
            return buildPlan("tokenBoosted", transformedText || originalText);

        if (/\b(trending tokens?|hot tokens?)\b/i.test(lowered))
            return buildPlan("tokenTrending", transformedText || originalText);

        if (/\b(most mentioned|mentioned ticker|top mentions|most talked)\b/i.test(lowered))
            return buildPlan("tickerMentioned", transformedText || originalText);

        if (/\b(new listings?|newly listed|listed today)\b/i.test(lowered))
            return buildPlan("cryptoListing", transformedText || originalText);

        if (/\b(market sentiment|sentiment right now|current sentiment|market mood)\b/i.test(lowered))
            return buildPlan("cryptoSentiment", transformedText || originalText);

        if (/\b(total volume|highest volume|volume today)\b/i.test(lowered))
            return buildPlan("cryptoVolume", transformedText || originalText);

        if (/\b(news|headlines?)\b/i.test(lowered) && !/\bnew listings?\b/i.test(lowered))
            return buildPlan("cryptoNews", transformedText || originalText);

        if (/\b(chart|graph|plot)\b/i.test(lowered)) {
            if (hasSingleAddress)
                return buildPlan("tokenChart", transformedText || uniqueAddresses[0] || originalText);
            if (hasSingleTicker)
                return buildPlan("cryptoChart", transformedText || `$${tickers[0]}`);
            return null;
        }

        if (/\b(analysis|analyze|analyse|market analysis|trade setup|setup)\b/i.test(lowered)) {
            if (hasSingleAddress)
                return buildPlan("tokenAnalysis", transformedText || uniqueAddresses[0] || originalText);
            if (hasSingleTicker)
                return buildPlan("cryptoAnalysis", transformedText || `$${tickers[0]}`);
            return null;
        }

        if (/\b(fundamental|fundamentals|tokenomics|description|project info)\b/i.test(lowered)) {
            if (hasSingleAddress)
                return buildPlan("tokenFundamental", transformedText || uniqueAddresses[0] || originalText);
            if (hasSingleTicker)
                return buildPlan("cryptoFundamental", transformedText || `$${tickers[0]}`);
            return null;
        }

        if (/\b(price|quote|how much|worth|cost)\b/i.test(lowered)) {
            if (hasSingleAddress)
                return buildPlan("tokenPrice", transformedText || uniqueAddresses[0] || originalText);
            if (hasSingleTicker)
                return buildPlan("cryptoPrice", transformedText || `$${tickers[0]}`);
            return null;
        }

        if (hasSingleAddress)
            return buildPlan("tokenPrice", transformedText || uniqueAddresses[0] || originalText);

        if (hasSingleTicker)
            return buildPlan("cryptoPrice", transformedText || `$${tickers[0]}`);

        return null;
    }

    private normalizeMessageForMarketActions(text: string): string {
        if (/\$[A-Za-z0-9]+/.test(text))
            return text;

        if (!/\b(chart|graph|plot|analysis|analyze|analyse|price|quote|trade|long|short|buy|sell|news|mentions?|trending|volume|token|market|fundamental|sentiment)\b/i.test(text))
            return text;

        return text.replace(/\b([A-Za-z]{2,10})\b/g, (raw) => {
            const lower = raw.toLowerCase();
            const upper = raw.toUpperCase();

            if (MARKET_SYMBOL_STOPWORDS.has(upper))
                return raw;

            if (MARKET_SYMBOL_ALIASES.has(lower))
                return `$${upper}`;

            return raw;
        });
    }

    private hasPotentialMarketIntent(text: string) {
        const raw = String(text || "").trim();
        if (!raw)
            return false;

        if (MARKET_INTENT_PATTERN.test(raw))
            return true;

        if (this.extractOverrideAddresses(raw).length > 0)
            return true;

        if (this.extractUniqueMatches(raw, EVM_ADDRESS_PATTERN).length > 0)
            return true;

        if (this.extractUniqueMatches(raw, BASE58_ADDRESS_PATTERN).length > 0)
            return true;

        if (this.extractExplicitTickers(raw).length > 0)
            return true;

        const plainSymbols: string[] = raw.match(/\b[A-Za-z]{2,10}\b/g) || [];
        return plainSymbols.some((symbol) => MARKET_SYMBOL_ALIASES.has(symbol.toLowerCase()));
    }

    private shouldUseConversationalFastPath(text: string) {
        const raw = String(text || "").trim();
        if (!raw)
            return false;

        if (this.hasPotentialMarketIntent(raw))
            return false;

        return CONVERSATIONAL_FAST_PATH_PATTERN.test(raw) || raw.split(/\s+/).length <= 8;
    }

    private hasPotentialActionMarketIntent(text: string) {
        const raw = String(text || "").trim();
        if (!raw)
            return false;

        if (ACTION_MARKET_INTENT_PATTERN.test(raw))
            return true;

        if (this.extractOverrideAddresses(raw).length > 0)
            return true;

        if (this.extractUniqueMatches(raw, EVM_ADDRESS_PATTERN).length > 0)
            return true;

        if (this.extractUniqueMatches(raw, BASE58_ADDRESS_PATTERN).length > 0)
            return true;

        if (this.extractExplicitTickers(raw).length > 0)
            return true;

        const plainSymbols: string[] = raw.match(/\b[A-Za-z]{2,10}\b/g) || [];
        return plainSymbols.some((symbol) => MARKET_SYMBOL_ALIASES.has(symbol.toLowerCase()));
    }

    private hasPotentialAccountIntent(text: string) {
        const raw = String(text || "").trim();
        if (!raw)
            return false;

        return ACCOUNT_INTENT_PATTERN.test(raw);
    }

    private parsePacificaKnowledge(raw: string | null | undefined): PacificaKnowledgePayload | null {
        const parsed = this.safeParseJson(String(raw || ""));
        if (!parsed || typeof parsed !== "object")
            return null;

        return parsed as PacificaKnowledgePayload;
    }

    private shouldUseAccountFastPath(text: string, pacificaKnowledge?: string | null) {
        if (!this.hasPotentialAccountIntent(text))
            return false;

        if (this.hasPotentialActionMarketIntent(text))
            return false;

        const parsed = this.parsePacificaKnowledge(pacificaKnowledge);
        return Boolean(parsed);
    }

    private formatAccountNumber(value: unknown, fractionDigits = 2) {
        const numeric = Number(value);
        if (!Number.isFinite(numeric))
            return "N/A";
        return numeric.toLocaleString("en-US", {
            minimumFractionDigits: 0,
            maximumFractionDigits: fractionDigits,
        });
    }

    private buildPacificaAccountSummary(pacificaKnowledge?: string | null) {
        const parsed = this.parsePacificaKnowledge(pacificaKnowledge);
        if (!parsed)
            return "";

        const status = parsed.pacifica_status || {};
        const account = parsed.pacifica_account || {};
        const positions = Array.isArray(parsed.open_positions) ? parsed.open_positions : [];

        const positionLines = positions.slice(0, 6).map((position, index) => [
            `${index + 1}. ${String(position.symbol || "").toUpperCase()} ${String(position.side || "").toUpperCase()}`,
            `amount=${this.formatAccountNumber(position.amount, 6)}`,
            `entry=${this.formatAccountNumber(position.entry_price, 6)}`,
            `mark=${this.formatAccountNumber(position.mark_price, 6)}`,
            `pnl_usd=${this.formatAccountNumber(position.unrealized_pnl_usd, 4)}`,
            `pnl_pct=${this.formatAccountNumber(position.unrealized_pnl_pct, 2)}%`,
            `notional_usd=${this.formatAccountNumber(position.notional_usd, 2)}`,
            `margin_usd=${this.formatAccountNumber(position.margin_usd, 2)}`,
            `tp=${this.formatAccountNumber(position.take_profit_price, 6)}`,
            `sl=${this.formatAccountNumber(position.stop_loss_price, 6)}`,
            `liq=${this.formatAccountNumber(position.liquidation_price, 6)}`,
        ].join(" | "));

        return [
            "# LIVE PACIFICA ACCOUNT SNAPSHOT",
            `ready_to_execute=${Boolean(status.readyToExecute)}`,
            `account_missing=${Boolean(parsed.account_missing)}`,
            `equity_usd=${this.formatAccountNumber(account.equity_usd, 4)}`,
            `available_to_spend_usd=${this.formatAccountNumber(account.available_to_spend_usd, 4)}`,
            `available_to_withdraw_usd=${this.formatAccountNumber(account.available_to_withdraw_usd, 4)}`,
            `total_margin_used_usd=${this.formatAccountNumber(account.total_margin_used_usd, 4)}`,
            `positions_count=${this.formatAccountNumber(account.positions_count, 0)}`,
            `orders_count=${this.formatAccountNumber(account.orders_count, 0)}`,
            `maker_fee_rate=${this.formatAccountNumber(account.maker_fee_rate, 6)}`,
            `taker_fee_rate=${this.formatAccountNumber(account.taker_fee_rate, 6)}`,
            parsed.onboarding_hint ? `onboarding_hint=${parsed.onboarding_hint}` : "",
            "",
            positions.length ? "OPEN POSITIONS:" : "OPEN POSITIONS: none",
            ...positionLines,
        ].filter(Boolean).join("\n");
    }

    private extractReplyText(raw: string): string {
        const trimmed = raw.trim();
        if (!trimmed)
            return "";

        const withoutCodeFence = trimmed
            .replace(/^```(?:json|text)?/i, "")
            .replace(/```$/i, "")
            .trim();

        const outMatch = withoutCodeFence.match(/<out>([\s\S]*?)<\/out>/i);
        const candidate = outMatch?.[1]?.trim() || withoutCodeFence;

        try {
            const parsed = JSON.parse(candidate) as Content | { text?: string };
            if (typeof parsed?.text === "string" && parsed.text.trim())
                return parsed.text.trim();
        } catch {
        }

        return candidate
            .replace(/<hidden>[\s\S]*?<\/hidden>/gi, "")
            .replace(/^"+|"+$/g, "")
            .trim();
    }

    private parseLooseNumber(raw: string | null | undefined): number | null {
        if (!raw)
            return null;

        const normalized = raw
            .replace(/[,$\s]/g, "")
            .replace(/−/g, "-")
            .trim();
        const numeric = Number(normalized);
        return Number.isFinite(numeric) ? numeric : null;
    }

    private safeParseJson(raw: string): unknown {
        const trimmed = String(raw || "").trim();
        if (!trimmed)
            return null;

        const fencedMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
        const candidates = [
            fencedMatch?.[1] ?? null,
            trimmed,
            trimmed.match(/\{[\s\S]*\}/)?.[0] ?? null,
        ].filter((chunk): chunk is string => Boolean(chunk));

        for (const chunk of candidates) {
            try {
                return JSON.parse(chunk);
            } catch {
                continue;
            }
        }

        return null;
    }

    private normalizeTradeParserPayload(payload: unknown) {
        if (!payload || typeof payload !== "object")
            return null;

        const data = payload as Record<string, unknown>;
        const reason = typeof data.reason === "string" && data.reason.trim()
            ? data.reason.trim()
            : undefined;

        const symbolRaw = (data.symbol ?? data.ticker ?? data.asset ?? data.pair) as string | null | undefined;
        const symbol = String(symbolRaw || "").replace(/[^A-Za-z0-9]/g, "").toUpperCase();
        if (!symbol || MARKET_SYMBOL_STOPWORDS.has(symbol))
            return null;

        const sideRaw = String(data.side ?? data.direction ?? data.bias ?? "").trim().toUpperCase();
        const side = sideRaw === "SHORT" ? "SHORT" : sideRaw === "LONG" ? "LONG" : null;
        if (!side)
            return null;

        const entry = this.parseLooseNumber(String(data.entry ?? data.entry_price ?? data.price ?? data.ep ?? ""));
        const tp = this.parseLooseNumber(String(data.tp ?? data.take_profit ?? data.target ?? data.target_price ?? ""));
        const sl = this.parseLooseNumber(String(data.sl ?? data.stop_loss ?? data.stop ?? data.invalid ?? ""));
        if (entry == null || tp == null || sl == null)
            return reason ? { symbol, side, entry, tp, sl, reason } : null;

        const isLongValid = side === "LONG" && sl < entry && entry < tp;
        const isShortValid = side === "SHORT" && tp < entry && entry < sl;
        if (!isLongValid && !isShortValid)
            return reason ? { symbol, side, entry, tp, sl, reason } : null;

        return { symbol, side, entry, tp, sl, reason };
    }

    private extractProposalTimeframe(rawText: string) {
        return rawText.match(/\$[A-Z0-9]{2,12}\s*-\s*([0-9]{1,3}[MHDW])\s*-/i)?.[1]?.toUpperCase() || "1H";
    }

    private extractProposalThesis(rawText: string, side: TradeProposal["side"], symbol: string, actionName: string) {
        const thesisBlock = rawText.match(/\bACTION STRATEGY:\s*([\s\S]*?)(?:\n\s*[◻📣]|$)/i)?.[1]?.trim()
            || rawText.match(/\bCONSIDERATIONS:\s*([\s\S]*?)(?:\n\s*[📣]|$)/i)?.[1]?.trim()
            || rawText.trim();

        return thesisBlock
            .replace(/\s+/g, " ")
            .replace(/^\W+|\W+$/g, "")
            .slice(0, 320)
            || `${side} ${symbol} setup extracted from ${actionName}`;
    }

    private buildTradeParserPrompt(actionName: string, rawText: string) {
        return [
            TRADE_PARSER_SYSTEM_PROMPT,
            "",
            `ACTION: ${actionName}`,
            "SOURCE MESSAGE:",
            "```",
            rawText,
            "```",
            "",
            "Notes:",
            "- Prefer the primary actionable setup described in the message.",
            "- If the text says entry is around/near/at a given price, use that price.",
            "- Do not mistake indicator names like EMA24 or EMA168 for price levels.",
        ].join("\n");
    }

    public async deriveProposalFromContent(content: Content): Promise<TradeProposal | undefined> {
        const actionName = String(content.action || "").trim().toUpperCase();
        if (!TRADE_PROPOSAL_ACTIONS.has(actionName))
            return undefined;

        const rawText = String(content.text || "");
        if (!rawText.trim())
            return undefined;

        let parsedProposal: ReturnType<AirificaMessageManager["normalizeTradeParserPayload"]> = null;
        try {
            const parserResponse = await this.withTimeout(
                `generateText(trade-parser:${actionName})`,
                generateText({
                    runtime: this.runtime,
                    context: this.buildTradeParserPrompt(actionName, rawText),
                    modelClass: ModelClass.LARGE,
                }),
                this.tradeParserTimeoutMs
            );
            parsedProposal = this.normalizeTradeParserPayload(this.safeParseJson(parserResponse));
        } catch (error) {
            elizaLogger.warn(`[client-airifica] trade parser failed for ${actionName}:`, error);
        }

        if (!parsedProposal || parsedProposal.entry == null || parsedProposal.tp == null || parsedProposal.sl == null) {
            elizaLogger.warn("[client-airifica] proposal skipped: no valid structured trade parsed", {
                actionName,
                rawText: rawText.slice(0, 320),
                reason: parsedProposal?.reason || null,
            });
            return undefined;
        }

        const symbol = parsedProposal.symbol;
        const side = parsedProposal.side as TradeProposal["side"];
        const timeframe = this.extractProposalTimeframe(rawText);
        const thesis = this.extractProposalThesis(rawText, side, symbol, actionName);

        return {
            symbol,
            side,
            entry: parsedProposal.entry,
            tp: parsedProposal.tp,
            sl: parsedProposal.sl,
            timeframe,
            confidence: actionName.includes("CHART") ? 0.72 : 0.66,
            thesis,
            sourceAction: actionName,
        };
    }

    private async routeMessageForActions(originalText: string): Promise<RoutedActionPlan> {
        const parseRouterOutput = (formatted: string, source: RoutedActionPlan["source"]): RoutedActionPlan => {
            const outMatch = formatted.match(/<out>([\s\S]*?)<\/out>/i);
            const routedPayload = outMatch?.[1]?.trim() || formatted;
            const hiddenMatch = routedPayload.match(/<hidden>([\s\S]*?)<\/hidden>/i);
            const hidden = hiddenMatch?.[1]?.trim() || "";
            const visibleText = routedPayload
                .replace(/<hidden>[\s\S]*?<\/hidden>/gi, "")
                .replace(/^"+|"+$/g, "")
                .trim();
            const firstDirective = hidden
                .split(/[;,]/)
                .map((part) => part.trim())
                .find(Boolean) || "";
            const keyword = firstDirective.toLowerCase() === "no action tools" ? null : firstDirective;
            const routedText = keyword
                ? `${keyword} ${visibleText || originalText}`.trim()
                : (visibleText || originalText).trim();

            return {
                keyword,
                routedText,
                raw: formatted,
                source,
                candidateActions: this.resolveRouteCandidateActions(keyword),
            };
        };

        const runRouter = async (modelClass: ModelClass, source: RoutedActionPlan["source"]) => {
            const formatted = (await this.withTimeout(
                `generateText(action-router:${source})`,
                generateText({
                    runtime: this.runtime,
                    context: buildActionRoutingPrompt(originalText),
                    modelClass,
                }),
                this.llmTimeoutMs
            )).replace(/<think>[\s\S]*?<\/think>/gi, "").trim();

            return parseRouterOutput(formatted, source);
        };

        const smallPlan = await runRouter(ModelClass.SMALL, "llm-small");
        const shouldRetryWithLarge = !smallPlan.keyword
            && ACTION_ROUTER_HIGH_SIGNAL_PATTERN.test(originalText)
            && !this.buildDeterministicActionRoute(originalText, this.normalizeMessageForMarketActions(originalText));

        if (!shouldRetryWithLarge)
            return smallPlan;

        elizaLogger.info("[client-airifica] action-router escalate", {
            originalText,
            smallKeyword: smallPlan.keyword,
            smallSource: smallPlan.source,
        });

        return await runRouter(ModelClass.LARGE, "llm-large");
    }

    private async runManualMandatoryActions(
        memory: Memory,
        state: State,
        actionCallback: HandlerCallback
    ): Promise<{ handled: boolean; routePlan: RoutedActionPlan }> {
        const originalText = typeof memory.content === "string"
            ? memory.content
            : memory.content?.text || "";

        if (!originalText.trim())
            return {
                handled: false,
                routePlan: {
                    keyword: null,
                    routedText: originalText,
                    raw: originalText,
                    source: "deterministic",
                    candidateActions: [],
                },
            };

        if (!this.hasPotentialMarketIntent(originalText))
            return {
                handled: false,
                routePlan: {
                    keyword: null,
                    routedText: originalText,
                    raw: originalText,
                    source: "deterministic",
                    candidateActions: [],
                },
            };

        let routePlan: RoutedActionPlan = {
            keyword: null,
            routedText: originalText,
            raw: originalText,
            source: "llm-small",
            candidateActions: [],
        };

        try {
            const deterministic = this.buildDeterministicActionRoute(
                originalText,
                this.normalizeMessageForMarketActions(originalText),
            );
            if (deterministic) {
                routePlan = deterministic;
                elizaLogger.info("[client-airifica] action-router", {
                    originalText,
                    routedText: routePlan.routedText,
                    keyword: routePlan.keyword,
                    source: routePlan.source,
                    raw: routePlan.raw,
                });
            } else {
                routePlan = await this.routeMessageForActions(originalText);
                elizaLogger.info("[client-airifica] action-router", {
                    originalText,
                    routedText: routePlan.routedText,
                    keyword: routePlan.keyword,
                    source: routePlan.source,
                    raw: routePlan.raw,
                });
            }
        } catch (error) {
            elizaLogger.warn("[client-airifica] action-router fallback to original text:", error);
        }

        if (!routePlan.keyword || routePlan.candidateActions.length === 0)
            return { handled: false, routePlan };

        const routedMemory: Memory = {
            ...memory,
            content: {
                ...(typeof memory.content === "string" ? { text: memory.content } : memory.content),
                text: routePlan.routedText,
            },
        };

        const airemarketPlugin = await this.getAirmarketPlugin();
        const validatedActions = new Map<string, any>();
        const mandatoryActions = new Set(this.getMandatoryActions());
        const candidateActions = new Set(
            routePlan.candidateActions.filter((actionName) =>
                mandatoryActions.size === 0 || mandatoryActions.has(actionName)
            )
        );
        const pluginActions = (airemarketPlugin.actions ?? []).filter((action: any) =>
            !!action && typeof action.name === "string"
        && candidateActions.has(action.name)
        );
        const singleCandidate = routePlan.candidateActions.length === 1;

        for (const action of pluginActions) {
            try {
                const isValid = await this.withTimeout(
                    `validate(${action.name})`,
                    Promise.resolve(action.validate(this.runtime, routedMemory, state)),
                    this.actionValidationTimeoutMs
                );
                if (isValid) {
                    validatedActions.set(action.name, action);
                    if (singleCandidate)
                        break;
                }
            } catch (error) {
                const details = error instanceof Error
                    ? `${error.message}\n${error.stack ?? ""}`.trim()
                    : String(error);
                elizaLogger.warn(`[client-airifica] manual validate failed for ${action.name}: ${details}`);
            }
        }

        for (const mandatoryAction of this.getMandatoryActions()) {
            const action = validatedActions.get(mandatoryAction);
            if (!action?.handler)
                continue;

            try {
                const handled = await this.withTimeout(
                    `handler(${action.name})`,
                    Promise.resolve(action.handler(this.runtime, routedMemory, state, {}, actionCallback)),
                    this.getActionHandlerTimeoutMs(action.name)
                );
                if (handled)
                    return { handled: true, routePlan };
            } catch (error) {
                const details = error instanceof Error
                    ? `${error.message}\n${error.stack ?? ""}`.trim()
                    : String(error);
                elizaLogger.warn(`[client-airifica] manual handler failed for ${action.name}: ${details}`);
            }
        }

        return { handled: false, routePlan };
    }

    private async generateConversationalResponse(state: State): Promise<Content | null> {
        const sanitizedState: State = state.recentMessages
            ? { ...state, recentMessages: state.recentMessages.replace(/<\|ACT:[^|]*\|>\s*/g, '') }
            : state;

        const baseTemplate = this.runtime.character.templates?.messageHandlerTemplate || AIRIFICA_DEFAULT_TEMPLATE;
        const responseTemplate = typeof baseTemplate === 'string'
            ? (baseTemplate.includes('{{pacificaContextBlock}}')
                ? baseTemplate
                : `${baseTemplate}\n\n{{pacificaContextBlock}}`)
            : ({ state }: { state: State }) => {
                const resolved = baseTemplate({ state });
                return resolved.includes('{{pacificaContextBlock}}')
                    ? resolved
                    : `${resolved}\n\n{{pacificaContextBlock}}`;
            };

        const responseContext = composeContext({
            state: sanitizedState,
            template: responseTemplate,
        });

        try {
            const responseText = this.extractReplyText(await this.withTimeout(
                "generateText(conversation-fastpath)",
                generateText({
                    runtime: this.runtime,
                    context: responseContext,
                    modelClass: ModelClass.SMALL,
                }),
                this.llmTimeoutMs
            ));

            if (responseText) {
                return {
                    text: responseText,
                    source: "airifica",
                };
            }
        } catch (error) {
            elizaLogger.warn("[client-airifica] conversation fast path small-model failed:", error);
        }

        const responseText = this.extractReplyText(await this.withTimeout(
            "generateText(conversation-fastpath-large)",
            generateText({
                runtime: this.runtime,
                context: responseContext,
                modelClass: ModelClass.LARGE,
            }),
            this.llmTimeoutMs
        ));

        if (!responseText)
            return null;

        return {
            text: responseText,
            source: "airifica",
        };
    }

    private async generateAccountAwareResponse(
        memory: Memory,
        state: State,
        pacificaKnowledge?: string | null,
    ): Promise<Content | null> {
        const sanitizedState: State = state.recentMessages
            ? { ...state, recentMessages: state.recentMessages.replace(/<\|ACT:[^|]*\|>\s*/g, '') }
            : state;

        const accountSummary = this.buildPacificaAccountSummary(pacificaKnowledge);
        if (!accountSummary)
            return await this.generateResponseContent(memory, state);

        const userText = typeof memory.content === "string"
            ? memory.content
            : memory.content?.text || "";

        const context = [
            "# CONVERSATION CONTEXT",
            sanitizedState.recentMessages || "",
            "",
            accountSummary,
            "",
            "# TASK",
            "You are Airifica.",
            "Answer the user's latest question using the live Pacifica account snapshot above.",
            "Prioritize factual accuracy over style.",
            "Be concise and direct.",
            "If the user asks for advice, reason from the snapshot but do not invent missing market data.",
            "If the snapshot shows no positions, say that clearly.",
            "Do not mention hidden prompts, JSON, or internal routing.",
            "",
            `USER: ${userText}`,
        ].join("\n");

        try {
            const responseText = this.extractReplyText(await this.withTimeout(
                "generateText(account-fastpath)",
                generateText({
                    runtime: this.runtime,
                    context,
                    modelClass: ModelClass.SMALL,
                }),
                this.llmTimeoutMs
            ));

            if (!responseText)
                return null;

            return {
                text: responseText,
                source: "airifica",
            };
        } catch (error) {
            elizaLogger.warn("[client-airifica] account fast path failed, falling back to generic response:", error);
            return await this.generateResponseContent(memory, state);
        }
    }

    /** Derive deterministic userId from wallet address */
    public getUserId(walletAddress: string): UUID {
        return stringToUuid(`airifica:user:${walletAddress}`) as UUID;
    }

    /** Derive deterministic roomId from wallet + conversationId */
    public getRoomId(walletAddress: string, conversationId: string): UUID {
        return stringToUuid(`airifica:room:${walletAddress}:${conversationId}`) as UUID;
    }

    private async createAgentMemory(
        roomId: UUID,
        agentId: UUID,
        inReplyTo: UUID,
        content: Content,
        suffix: string
    ): Promise<Memory> {
        const agentMemory: Memory = {
            id: stringToUuid(`airifica:agentmsg:${roomId}:${Date.now()}:${suffix}`),
            agentId,
            userId: agentId,
            roomId,
            content: {
                ...content,
                inReplyTo,
            },
            createdAt: Date.now(),
            embedding: getEmbeddingZeroVector(),
        };

        await this.runtime.messageManager.createMemory(agentMemory);
        return agentMemory;
    }

    private async generateResponseContent(memory: Memory, state: State): Promise<Content | null> {
        // Strip ACT tokens from recentMessages to prevent JSON parse errors in
        // generateMessageResponse. Old DB rows may contain poisoned content with
        // <|ACT: {"emotion": "..."}|> prefixes that cause DeepSeek to mimic the format.
        const sanitizedState: State = state.recentMessages
            ? { ...state, recentMessages: state.recentMessages.replace(/<\|ACT:[^|]*\|>\s*/g, '') }
            : state;

        const baseTemplate = this.runtime.character.templates?.messageHandlerTemplate || AIRIFICA_DEFAULT_TEMPLATE;
        const responseTemplate = typeof baseTemplate === 'string'
            ? (baseTemplate.includes('{{pacificaContextBlock}}')
                ? baseTemplate
                : `${baseTemplate}\n\n{{pacificaContextBlock}}`)
            : ({ state }: { state: State }) => {
                const resolved = baseTemplate({ state });
                return resolved.includes('{{pacificaContextBlock}}')
                    ? resolved
                    : `${resolved}\n\n{{pacificaContextBlock}}`;
            };

        const responseContext = composeContext({
            state: sanitizedState,
            template: responseTemplate,
        });

        try {
            const response = await this.withTimeout(
                "generateMessageResponse(fallback)",
                generateMessageResponse({
                    runtime: this.runtime,
                    context: responseContext,
                    modelClass: ModelClass.SMALL,
                }),
                this.llmTimeoutMs
            );

            if (response && (response.text || response.action)) {
                const text = response.text ? this.extractReplyText(response.text) : "";
                return {
                    ...response,
                    text,
                    source: "airifica",
                };
            }
        } catch (error) {
            elizaLogger.warn("[client-airifica] generateMessageResponse fallback failed, switching to plain text:", error);
        }

        const responseText = this.extractReplyText(await this.withTimeout(
            "generateText(fallback)",
            generateText({
                runtime: this.runtime,
                context: responseContext,
                modelClass: ModelClass.LARGE,
            }),
            this.llmTimeoutMs
        ));

        if (!responseText)
            return null;

        return {
            text: responseText,
            source: "airifica",
        };
    }

    private async generateMarketChatResponse(state: State): Promise<Content | null> {
        const sanitizedState: State = state.recentMessages
            ? { ...state, recentMessages: state.recentMessages.replace(/<\|ACT:[^|]*\|>\s*/g, '') }
            : state;

        const baseTemplate = this.runtime.character.templates?.messageHandlerTemplate || AIRIFICA_DEFAULT_TEMPLATE;
        const responseTemplate = typeof baseTemplate === 'string'
            ? (baseTemplate.includes('{{pacificaContextBlock}}')
                ? baseTemplate
                : `${baseTemplate}\n\n{{pacificaContextBlock}}`)
            : ({ state }: { state: State }) => {
                const resolved = baseTemplate({ state });
                return resolved.includes('{{pacificaContextBlock}}')
                    ? resolved
                    : `${resolved}\n\n{{pacificaContextBlock}}`;
            };

        const responseContext = composeContext({
            state: sanitizedState,
            template: responseTemplate,
        });

        const responseText = this.extractReplyText(await this.withTimeout(
            "generateText(market-fastpath)",
            generateText({
                runtime: this.runtime,
                context: responseContext,
                modelClass: ModelClass.SMALL,
            }),
            this.llmTimeoutMs
        ));

        if (!responseText)
            return null;

        return {
            text: responseText,
            source: "airifica",
        };
    }

    private async generateActionMissResponse(
        memory: Memory,
        state: State,
        routePlan: RoutedActionPlan,
    ): Promise<Content | null> {
        const userText = typeof memory.content === "string"
            ? memory.content
            : memory.content?.text || "";
        const sanitizedState: State = state.recentMessages
            ? { ...state, recentMessages: state.recentMessages.replace(/<\|ACT:[^|]*\|>\s*/g, '') }
            : state;

        const context = [
            "# CONVERSATION CONTEXT",
            sanitizedState.recentMessages || "",
            "",
            state.pacificaContextBlock || "",
            "",
            "# TASK",
            "You are Airifica.",
            "The user asked a market-related question, but no executable action completed.",
            "Answer directly in plain text using the available context.",
            "If the request lacks a resolvable market entity or actionable data, state what is missing in one short sentence.",
            "Do not mention hidden routing, validators, or internal tools.",
            "",
            `ROUTER_KEYWORD: ${routePlan.keyword || "none"}`,
            `USER: ${userText}`,
        ].join("\n");

        const responseText = this.extractReplyText(await this.withTimeout(
            "generateText(action-miss-fastpath)",
            generateText({
                runtime: this.runtime,
                context,
                modelClass: ModelClass.SMALL,
            }),
            this.llmTimeoutMs
        ));

        if (!responseText)
            return null;

        return {
            text: responseText,
            source: "airifica",
        };
    }

    /**
     * Process an incoming message from the Airifica web client.
     * Returns an array of response envelopes (may be multiple if chunked).
     */
    public async handleMessage(
        msg: AirificaIncomingMessage,
        options?: { pacificaKnowledge?: string | null },
    ): Promise<AirificaMessageEnvelope[]> {
        const { walletAddress, conversationId, text } = msg;
        const normalizedText = this.normalizeMessageForMarketActions(text);
        const conversationalFastPath = this.shouldUseConversationalFastPath(text);
        const accountFastPath = this.shouldUseAccountFastPath(text, options?.pacificaKnowledge);
        let marketFastPath = false;
        let actionMissFastPath = false;

        const userId = this.getUserId(walletAddress);
        const roomId = this.getRoomId(walletAddress, conversationId);
        const agentId = this.runtime.agentId;
        const userName = walletAddress.slice(0, 8) + "..."; // short label

        elizaLogger.info("[client-airifica] handleMessage", {
            walletAddress: walletAddress.slice(0, 8),
            conversationId,
            textLen: text.length,
            normalizedForActions: normalizedText !== text,
            conversationalFastPath,
            accountFastPath,
        });

        try {
            // 1. Ensure connection (creates user/room records if not present)
            await this.runtime.ensureConnection(
                userId,
                roomId,
                userName,
                walletAddress,
                "airifica"
            );

            // 2. Build memory for the user message
            const messageId = stringToUuid(`airifica:msg:${roomId}:${Date.now()}`) as UUID;
            const content: Content = {
                text: normalizedText,
                source: "airifica",
            };
            const memory: Memory = {
                id: messageId,
                agentId,
                userId,
                roomId,
                content,
                createdAt: Date.now(),
                embedding: getEmbeddingZeroVector(),
            };
            await this.runtime.messageManager.createMemory(memory);

            // 3. Compose state
            let state = await this.runtime.composeState(memory, {
                agentName: this.runtime.character.name,
            });
            state = await this.runtime.updateRecentMessageState(state);

            // 4. Collected response envelopes
            const responses: AirificaMessageEnvelope[] = [];
            let actionSent = false;

            // 5. Action callback — called by processActions when an action fires
            const actionCallback: HandlerCallback = async (actionContent: Content) => {
                actionSent = true;
                const envelope = this.contentToEnvelope(conversationId, actionContent);
                responses.push(envelope);

                const agentMemory = await this.createAgentMemory(
                    roomId,
                    agentId,
                    messageId,
                    actionContent,
                    "action"
                );
                return [agentMemory];
            };

            // 6. Pre-action phase: manual air3market router with the same keyword/action contract.
            const actionRoutingResult: { handled: boolean; routePlan: RoutedActionPlan } = (conversationalFastPath || accountFastPath)
                ? { handled: false, routePlan: {
                    keyword: null,
                    routedText: normalizedText,
                    raw: normalizedText,
                    source: "deterministic",
                    candidateActions: [],
                } }
                : await this.runManualMandatoryActions(memory, state, actionCallback);
            const preActionHandled = actionRoutingResult.handled;
            marketFastPath = !conversationalFastPath
                && !accountFastPath
                && !preActionHandled
                && actionRoutingResult.routePlan.keyword == null
                && this.hasPotentialActionMarketIntent(text);
            actionMissFastPath = !conversationalFastPath
                && !accountFastPath
                && !preActionHandled
                && actionRoutingResult.routePlan.keyword != null;

            // 7. If an action already replied, stop here
            if (actionSent || preActionHandled) {
                if (!conversationalFastPath) {
                    this.runBestEffort(
                        "evaluate(action)",
                        () => this.runtime.evaluate(memory, state, true),
                        this.evaluationTimeoutMs
                    );
                }
                return responses;
            }

            // 8. Fallback LLM: no action handled the message.
            // Use structured generation first so post-actions keep parity with Telegram.
            const responseState = {
                ...state,
                pacificaContextBlock: this.buildPacificaContextBlock(options?.pacificaKnowledge),
            };
            const responseContent = accountFastPath
                ? await this.generateAccountAwareResponse(memory, responseState, options?.pacificaKnowledge)
                : conversationalFastPath
                    ? await this.generateConversationalResponse(responseState)
                    : marketFastPath
                        ? await this.generateMarketChatResponse(responseState)
                        : actionMissFastPath
                            ? await this.generateActionMissResponse(memory, responseState, actionRoutingResult.routePlan)
                        : await this.generateResponseContent(memory, responseState);

            if (!responseContent || (!responseContent.text && !responseContent.action && !(responseContent as any).proposal && !(responseContent as any).image)) {
                if (!conversationalFastPath && !accountFastPath && !marketFastPath && !actionMissFastPath) {
                    this.runBestEffort(
                        "evaluate(empty-response)",
                        () => this.runtime.evaluate(memory, state, false),
                        this.evaluationTimeoutMs
                    );
                }
                return responses;
            }

            // 9. Persist and dispatch the model reply, then allow post-actions to react to it.
            const action = this.runtime.actions.find(a => a.name === responseContent.action);
            const shouldSuppressInitialMessage = !!action?.suppressInitialMessage;

            if (!shouldSuppressInitialMessage) {
                responses.push(this.contentToEnvelope(conversationId, responseContent));
                await this.createAgentMemory(roomId, agentId, messageId, responseContent, "llm");
            } else {
                await this.createAgentMemory(roomId, agentId, messageId, responseContent, "llm-suppressed");
            }
            // 10. Evaluate
            if (!conversationalFastPath && !accountFastPath && !marketFastPath && !actionMissFastPath) {
                this.runBestEffort(
                    "evaluate(final)",
                    () => this.runtime.evaluate(memory, state, true),
                    this.evaluationTimeoutMs
                );
            }

            return responses;
        } catch (error: any) {
            elizaLogger.error("[client-airifica] handleMessage error:", error);
            return [
                {
                    ok: false,
                    conversationId,
                    message: { text: "An error occurred. Please try again." },
                    error: error?.message || "unknown",
                },
            ];
        }
    }

    /**
     * Fetch conversation history (recent memories for the room).
     */
    public async getHistory(walletAddress: string, conversationId: string, count = 20): Promise<AirificaMessageEnvelope[]> {
        const roomId = this.getRoomId(walletAddress, conversationId);
        try {
            const memories = await this.runtime.messageManager.getMemories({
                roomId,
                count,
            });
            return await Promise.all(memories.map(async (m) => {
                return this.contentToEnvelope(
                    conversationId,
                    m.content,
                    { includeDerivedProposal: true }
                );
            }));
        } catch {
            return [];
        }
    }

    /** Convert a Content object to a normalized AirificaMessageEnvelope */
    private contentToEnvelope(
        conversationId: string,
        content: Content,
        options?: { includeDerivedProposal?: false }
    ): AirificaMessageEnvelope;
    private async contentToEnvelope(
        conversationId: string,
        content: Content,
        options: { includeDerivedProposal: true }
    ): Promise<AirificaMessageEnvelope>;
    private contentToEnvelope(
        conversationId: string,
        content: Content,
        options?: { includeDerivedProposal?: boolean }
    ): AirificaMessageEnvelope | Promise<AirificaMessageEnvelope> {
        const msg: AirificaMessageContent = {
            text: content.text,
            action: content.action,
        };

        // Extract image if present
        if ((content as any).image) {
            msg.image = (content as any).image;
        }
        if (content.attachments?.length) {
            const imgAttachment = content.attachments.find(
                (a) => a.contentType?.startsWith("image/")
            );
            if (imgAttachment?.url) {
                msg.image = imgAttachment.url;
            }
        }

        // Extract structured proposal if present
        if ((content as any).proposal) {
            msg.proposal = (content as any).proposal;
        }
        if ((content as any).content?.proposal) {
            msg.proposal = (content as any).content.proposal;
        }

        msg.meta = { source: "airifica", provider: "plugin-airemarket" };

        const envelope: AirificaMessageEnvelope = {
            ok: true,
            conversationId,
            message: msg,
        };

        if (!options?.includeDerivedProposal || msg.proposal) {
            return envelope;
        }

        return this.deriveProposalFromContent(content).then((proposal) => {
            if (proposal)
                envelope.message.proposal = proposal;

            return envelope;
        });
    }
}
